language: python
python:
    - '3.5'
    - '3.6'
    - '3.7'
cache: pip
sudo: false
install:
    - deactivate
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION statsmodels seaborn patsy tqdm pytables
    - source activate test-environment
    - python setup.py install
script:
    - pytest tests
after_success:
    - pip install sphinx sphinx_rtd_theme
    - cd docs
    - make html
    - touch build/html/.nojekyll
deploy:
    provider: pages
    skip_cleanup: try
    github_token: $GITHUB_TOKEN
    keep-history: true
    on:
        branch: master
    target_branch: gh-pages # that's the default anyway, just to be explicit
    local_dir: docs/build/html
