env:
    - PACKAGE_NAME: fitgrid  # for the conda_upload.sh deploy script
language: minimal
before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - source $HOME/miniconda/etc/profile.d/conda.sh && conda activate
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda install -q conda-build conda-verify
    - conda info -a
install:
    - conda build conda -c kutaslab  # for pymer4
    - conda convert -p all /home/travis/miniconda/conda-bld/linux-64/fitgrid-*.tar.bz2
    - conda create --name fitgrid_env -c kutaslab pymer4
    - conda activate fitgrid_env  # so tests run in env as installed by conda
    - conda install -c local fitgrid  # install after or conda chooses v0.2.2 !?
    - conda install black pytest-cov
    - conda list
    - lscpu
    - python -c 'import numpy; numpy.show_config()'
script:
    - black --check --verbose -S --line-length=79 .
    - pytest --cov=fitgrid
after_success:
    - pip install codecov && codecov
# before_deploy:
deploy:
    - provider: script
      skip_cleanup: true
      script: bash ./ci/conda_upload.sh
      on:
          # ok for testing, conda uploads can be deleted and file names reused
          all_branches: true
          # tags: true
          # condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$  # match vN.N.N

    # homegrown replacement for TravisCI gh_pages provider
    - provider: script
      skip_cleanup: true
      script: bash ./ci/ghpages_upload.sh
      on:
          all_branches: true   # testing only
          # tags: true
          # condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$

    - provider: pypi
      skip_cleanup: true
      user: "__token__"
      password: $PYPI_TOKEN
      on:
          # do NOT test PyPI on all_branches. file names are UUIDs
          # in PyPI repo database, can be deleted but not freed. Use
          # unique (disposable?) N.N.N.devN, aN, bN, rcN versions if
          # you must test deploy to PyPI
          tags: true
          condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
