env:
    - PACKAGE_NAME: fitgrid  # for the conda_upload.sh deploy script
language: minimal
before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - source $HOME/miniconda/etc/profile.d/conda.sh && conda activate
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda install -q conda-build conda-verify
    - conda info -a
install:

    #  09/03/20 build w/ 3.7, conda dependency solver fails ugly w/ py3.8
    - conda build conda --python 3.7 -c turbach/label/pre-release -c defaults -c conda-forge
    - conda create -n fitgrid_env fitgrid -c local -c turbach/label/pre-release -c defaults -c conda-forge
    - conda activate fitgrid_env
    - conda install black pytest-cov
    - conda list
    - lscpu
    - python -c 'import numpy; numpy.show_config()'
script:
    - black --check --verbose -S --line-length=79 .
    - pytest --cov=fitgrid
after_success:
    - pip install codecov && codecov
# before_deploy:
deploy:
    - provider: script
      skip_cleanup: true
      script: bash ./ci/conda_upload.sh
      on:
          # conda_upload.sh switches on the branch and version string for a
          # dry run or upload to conda label pre-release or label main
          all_branches: true

    # homegrown replacement for TravisCI gh_pages provider
    - provider: script
      skip_cleanup: true
      script: bash ./ci/ghpages_upload.sh
      on:
          # all_branches: true   # testing only
          branch: master  # allow doc updates to master between tagged releases

    - provider: pypi
      skip_cleanup: true
      user: "__token__"
      password: $PYPI_TOKEN
      on:
          # do NOT test PyPI on all_branches. file names are UUIDs
          # in PyPI repo database, can be deleted but not freed. Use
          # unique (disposable?) N.N.N.devN, aN, bN, rcN versions if
          # you must test deploy to PyPI
          tags: true
          condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
