sudo: false
language: python
python:
    - '3.6'
cache: pip
install:
    - pip install -r requirements.txt
    - pip install -U black pytest pytest-cov
script:
    - black --check --verbose -S --line-length=79 .
    - pytest --cov=fitgrid
after_success:
    - pip install codecov && codecov
    - pip install sphinx sphinx_rtd_theme
    - cd docs
    - make html
    - touch build/html/.nojekyll
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep-history: true
    on:
        branch: dev
    target_branch: gh-pages # that's the default anyway, just to be explicit
    local_dir: docs/build/html
