env:
    - PACKAGE_NAME: fitgrid  # for the conda_upload.sh deploy script
language: minimal
before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - source $HOME/miniconda/etc/profile.d/conda.sh && conda activate
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda install -q conda-build conda-verify
    - conda info -a
install:
    - conda build conda -c kutaslab  # for pymer4
    - conda convert -p all /home/travis/miniconda/conda-bld/linux-64/fitgrid-*.tar.bz2
    - conda create --name fitgrid_env -c kutaslab pymer4
    - conda activate fitgrid_env  # so tests run in env as installed by conda
    - conda install -c local fitgrid  # install after or conda chooses v0.2.2 !?
    - conda install black pytest-cov
    - conda list
    - lscpu
    - python -c 'import numpy; numpy.show_config()'
script:
    - black --check --verbose -S --line-length=79 .
    - pytest --cov=fitgrid
after_success:
    - pip install codecov && codecov
before_deploy:
    - pip install sphinx sphinx_rtd_theme jupyter nbsphinx nbconvert!=5.4
    - conda install -c conda-forge pandoc
    - pip install -e .  # install fitgrid locally so it can be imported in the notebook
    - conda list
    - make -C docs html
    - touch docs/build/html/.nojekyll
deploy:
    - provider: script
      skip_cleanup: true
      script: bash ./ci/conda_upload.sh
      on:
          all_branches: true  # ok for testing Anaconda tarball names can be reused
          # tags: true            # restrict to vN.N.N tags
          # condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$

    - provider: pages
      verbose: true
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      keep-history: true
      on:
          # update docs on vN.N.N release
          tags: true
          condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
      target_branch: gh-pages  # that's the default anyway, just to be explicit
      local_dir: docs/build/html

    - provider: pypi
      skip_cleanup: true
      user: "__token__"
      password: $PYPI_TOKEN
      on:
          # do NOT test PyPI on all_branches. file names are UUIDs
          # on PyPI, can be deleted but not freed. Use unique
          # N.N.N.devN, aN, bN, rcN versions if you must test deploy
          # to PyPI
          tags: true
          condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
