# usage:
#   conda env create -f environment.yml
#   conda activate fitgrid_compat
name: fitgrid_compat
channels:
    - kutaslab
dependencies:
    - pytest
    - pytest-cov
    - mro-base
    - rpy2
    - python=3.6
    - pymer4
    - r-lme4=1.1_17
    - r-lmerTest=3.0_1
    - numpy=1.15.4
    - scipy=1.2.1
    - pandas=0.24.1
    - matplotlib
    - statsmodels=0.9.0
    - pytables
    - pyarrow
    - patsy
    - tqdm
