# usage:
#   conda env create -f environment.yml
#   conda activate fitgrid_compat
name: fitgrid_compat
channels:
    - kutaslab
dependencies:
    - pytest
    - pytest-cov
    - rpy2
    - python=3.6
    - pymer4
    - r-lme4
    - r-lmerTest
    - numpy
    - scipy
    - pandas
    - matplotlib
    - statsmodels
    - pytables
    - pyarrow
    - patsy
    - tqdm
