{% set version = "0.5.0.dev1" %}

package:
  name: fitgrid
  version: {{ version }}

source:
  # path: ../
  git_url: ../  # triggers GIT_X_Y env vars on TravisCI

build:
  # setting string embeds git short SHA in conda tarball name
  # script: python setup.py install --single-version-externally-managed --record=record.txt
  script: pip install . -vv --no-deps
  # github vN.N.N release builds are tagged with git short hash and conda build number, Travis deploys should be 0
  string: {{ environ.get('GIT_BUILD_STR', "no_GIT_BUILD_STR") }}_{{ environ.get("PKG_BUILDNUM", "no_PKG_BUILDNUM") }}

requirements:
#  build:

  host:
    - python
    - pip

  run:
    - python >=3.6
    - pymer4
    - statsmodels
    - pandas
    - numpy
    - matplotlib
    - scipy
    - pyarrow >=1.0   # else picks up conda main 0.15 of 09/03/20
    - pytables
    - tqdm

test:
  imports:
    - fitgrid
    - pymer4

about:
  home: https://github.com/kutaslab/fitgrid
  license: BSD
  license_file: LICENSE
