{% set version = "0.4.5" %}
{% set np_pin = "1.16.4" %}
{% set py_pin = "3.6" %}

package:
    name: fitgrid
    version: {{ version }}

source:
    # path: ../
    git_url: ../  # triggers GIT_X_Y env vars on TravisCI

build:
    # setting string embeds git short SHA in conda tarball name
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: {{ environ.get('GIT_BUILD_STR', "no_tags_on_travis_br") }}  # github release builds are tagged

requirements:
    # build:
    #    - python
    host:
        - python ={{ py_pin }}
        - numpy <={{ np_pin }}

    run:
        - python ={{ py_pin }}
        - rpy2
        - pymer4
        - r-lme4
        - r-lmerTest
        - numpy <={{ np_pin }}
        - scipy
        - pandas
        - matplotlib
        - statsmodels
        - pytables
        - pyarrow
        - patsy
        - tqdm

test:
    imports:
        - fitgrid
        - pymer4

about:
    home: https://github.com/kutaslab/fitgrid
    license: BSD
    license_file: LICENSE
