package:
    name: fitgrid
    version: "0.4.3-dev"

source:
    path: ../

build:
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python

    run:
        - python=3.6
        - rpy2
        - pymer4
        - r-lme4
        - r-lmerTest
        - numpy=1.15.4
        - scipy
        - pandas
        - matplotlib
        - statsmodels
        - pytables
        - patsy
        - tqdm

test:
    imports:
        - fitgrid
        - pymer4

about:
    home: https://github.com/kutaslab/fitgrid
    license: BSD
    license_file: LICENSE
