{% set version = "0.4.9.dev0" %}
# {% set np_pin = "1.16.4" %}
{% set py_pin = "3.6" %}

package:
    name: fitgrid
    version: {{ version }}

source:
    # path: ../
    git_url: ../  # triggers GIT_X_Y env vars on TravisCI

build:
    # setting string embeds git short SHA in conda tarball name
    script: python setup.py install --single-version-externally-managed --record=record.txt
    # github vN.N.N release builds are tagged with git short hash and conda build number, Travis deploys should be 0
    string: {{ environ.get('GIT_BUILD_STR', "no_GIT_BUILD_STR") }}_{{ environ.get("PKG_BUILDNUM", "no_PKG_BUILDNUM") }}

requirements:
    # build:
    #    - python
    host:
        - python ={{ py_pin }}
        # - numpy <={{ np_pin }}
        - numpy

    run:
        - python ={{ py_pin }}
        - rpy2
        - pymer4
        - r-lme4
        - r-lmerTest
        # - numpy # <={{ np_pin }}
        - numpy
        - scipy
        - pandas
        - matplotlib
        - statsmodels
        - pytables
        - pyarrow
        - patsy
        - tqdm

test:
    imports:
        - fitgrid
        - pymer4

about:
    home: https://github.com/kutaslab/fitgrid
    license: BSD
    license_file: LICENSE
